(()=>{
 'use strict';
 const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e};
 const dialog=node('dialog',null);dialog.id='live-monitor';dialog.setAttribute('aria-labelledby','lm-title');
 dialog.innerHTML=`<div class="lm-shell"><div class="lm-head"><div class="lm-brand"><span class="lm-icon" aria-hidden="true">▥</span><div><div class="lm-eyebrow">NETCHECKER · LIVE MONITOR</div><h2 id="lm-title">실시간 네트워크 관제</h2></div></div><div class="lm-tools"><span class="lm-muted" id="lm-update">연결 중</span><button id="lm-expand" type="button">전체화면</button><button id="lm-close" type="button" autofocus>닫기 ✕</button></div></div><div class="lm-period-bar"><label>기간 <select id="lm-period" aria-label="전체 관제 조회 기간"><option value="live">실시간</option><option value="1">최근 1시간</option><option value="2">최근 2시간</option><option value="4">최근 4시간</option><option value="6">최근 6시간</option><option value="8">최근 8시간</option><option value="12">최근 12시간</option><option value="24">최근 24시간</option></select></label><span id="lm-period-note" class="lm-muted">서버 · TOP 5 · TOP 50 공통 적용</span></div><div id="lm-error" class="lm-error" role="status" hidden></div><div class="lm-stats" id="lm-stats"></div><div class="lm-layout"><section class="lm-left"><div class="lm-section-head"><h3 id="lm-server-title">서버 통신 현황</h3><span class="lm-muted" id="lm-server-count"></span></div><div class="lm-server-list" id="lm-servers"><p class="lm-loading">수집 자료를 불러오고 있습니다.</p></div></section><section class="lm-right"><div><div class="lm-section-head"><h3 id="lm-top-title">PC 통신량 TOP 5</h3><span class="lm-muted" id="lm-top-note">최근 수집 속도 · 송신 + 수신</span></div><div class="lm-top5" id="lm-top5"></div></div><div class="lm-table-panel"><div class="lm-table-head"><div><h3 id="lm-ranking-title">PC 통신량 TOP 50</h3><p class="lm-muted">이름 · IP · 송수신 · 자원 · 이상 징후</p></div><div class="lm-ranking-controls"><label><input type="checkbox" id="lm-alert-only">주의·경고만</label></div></div><div class="lm-table-scroll"><table><thead><tr><th>순위</th><th>장비 · IP</th><th id="lm-tx-heading">송신 ↑</th><th id="lm-rx-heading">수신 ↓</th><th id="lm-total-heading">합계</th><th id="lm-resource-heading">CPU / RAM</th><th>상태 · 확인 사항</th></tr></thead><tbody id="lm-rows"></tbody></table></div><div class="lm-table-meta" id="lm-table-meta"></div></div></section></div><div class="lm-foot"><span>1분 단위 수집 · 화면 15초 갱신 · 인터넷 + 내부망 통신량</span><details><summary>주의·경고 기준 안내</summary><p>최근 5분 통신량이 이전 6시간 평균의 1.5배 이상이면 주의, 3배 이상이면 경고입니다. 두 구간 모두 유효 수집률 80% 이상일 때 비교하며, 기준 자료는 5분마다 갱신합니다. CPU 또는 메모리가 최근 3회 연속 90% 이상이면 주의, 95% 이상이면 경고입니다. 3분 넘게 수집되지 않으면 수집 지연으로 표시합니다. 표시만으로 루프·침해를 확정하지 않으며, AI 상세 조사는 대시보드 분석 버튼으로 실행합니다. 내부 통신은 송신·수신 장비 양쪽에서 집계될 수 있습니다.</p></details></div></div>`;
 document.body.append(dialog);const $=id=>document.getElementById(id);
 let timer=null,controller=null,last=null,epoch=0,previousOverflow='',ownsFullscreen=false;let ranking=null,rankingError='',rankingController=null,rankingVersion=0,rankingPending='';
 const n=value=>value==null?'—':value.toLocaleString('ko-KR',{maximumFractionDigits:2});
 const rate=value=>value==null?'—':n(value*8/1e6)+' Mbps';
 const amount=value=>value==null?'—':value>=1e9?n(value/1e9)+' GB':value>=1e6?n(value/1e6)+' MB':value>=1000?n(value/1000)+' KB':n(value)+' B';
 const clock=value=>value?new Date(value).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour12:false}):'미수집';
 const ip=d=>d.ips.length?d.ips.join(' / '):'표시할 IPv4 없음';
 function badge(d){const level=d.severity!=='none'?d.severity:d.state==='live'?'live':'';const text=d.severity==='warning'?'⚠ 경고':d.severity==='caution'?'△ 주의':d.state==='stale'?'◷ 수집 지연':d.state==='missing'?'수집 대기':d.state==='waiting'?'계측 대기':'● 수집 중';return node('span',text,'lm-badge '+level)}
 function resources(d){const wrap=node('div',null,'lm-resources');for(const [name,value,peak] of [['CPU',d.cpu,d.cpu_max],['RAM',d.ram,d.ram_max]]){const row=node('div');row.append(node('span',name+' '+(d.period?'평균 ':'현재 ')+(value==null?'—':n(value)+'%')),node('small','최고 '+(peak==null?'—':n(peak)+'%'),'lm-resource-peak'));wrap.append(row)}return wrap}
 function meters(d){return resources(d)}
 function spark(d){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 300 36');svg.setAttribute('class','lm-spark');svg.setAttribute('role','img');svg.setAttribute('aria-label',d.period?'선택 기간 통신 속도 추이':'최근 30분 통신 속도 추이');const points=d.trend||[];const valid=points.filter(x=>x.mbps!=null);if(!valid.length)return node('p','최근 통신 추이 자료가 없습니다.','lm-muted');const max=Math.max(...valid.map(x=>x.mbps),.01),end=Date.parse(d.window_end||last.generated_at),start=d.window_start?Date.parse(d.window_start):end-30*60000;let path='',prior=null;for(const p of points){const time=Date.parse(p.time);if(p.mbps==null){prior=null;continue}const x=Math.max(0,Math.min(300,(time-start)/(end-start)*300)),y=32-p.mbps/max*27;path+=(prior==null||time-prior>(d.period?d.trend_step_seconds*1500:90000)?'M':'L')+x.toFixed(2)+','+y.toFixed(2);prior=time}const line=document.createElementNS(ns,'path');line.setAttribute('d',path);line.setAttribute('fill','none');line.setAttribute('stroke','#59cdbd');line.setAttribute('stroke-width','2');svg.append(line);return svg}
 function serverCard(d){const card=node('article',null,'lm-card');const head=node('div',null,'lm-card-title'),title=node('div');title.append(node('div',d.label+' · 연결 '+(d.connected_client_count==null?'확인 불가':d.connected_client_count+'대'+(d.connections_partial?' 이상':'')),'lm-device'),node('div',ip(d),'lm-ip'));head.append(title,badge(d));const big=node('div',d.period?amount(d.total_bytes):rate(d.total_bps),'lm-main-rate');big.append(node('small',d.period?' 기간 누적':' 송수신 합계'));const duplex=node('div',null,'lm-duplex');duplex.append(node('span','↑ '+(d.period?amount(d.tx_bytes):rate(d.tx_bps)),'lm-tx'),node('span','↓ '+(d.period?amount(d.rx_bytes):rate(d.rx_bps)),'lm-rx'));card.append(head,big,duplex,spark(d),meters(d));card.append(node('p',d.period?'관측 평균 '+n(d.average_mbps)+' Mbps · 수집률 '+n(d.coverage_percent)+'%':d.interval_seconds?'최근 '+Math.round(d.interval_seconds)+'초 · 송신 '+amount(d.tx_bytes)+' / 수신 '+amount(d.rx_bytes):'유효한 최근 통신량 자료가 없습니다.','lm-muted'));for(const a of d.alerts)card.append(node('div',a.reason,'lm-reason'));const foot=node('div',null,'lm-last');foot.append(node('span','수집 '+clock(d.last_seen)),node('span',d.comparison));card.append(foot);return card}
 function topCard(d){const card=node('article',null,'lm-top-card');const title=node('div','#'+d.rank,'lm-top-rank');title.append(badge(d));const name=node('div',d.label,'lm-device');name.title=d.label;card.append(title,name,node('div',ip(d),'lm-ip'),node('div',d.period?amount(d.total_bytes):rate(d.total_bps),'lm-main-rate'));const duplex=node('div',null,'lm-duplex');duplex.append(node('div','↑ '+(d.period?amount(d.tx_bytes):rate(d.tx_bps)),'lm-tx'),node('div','↓ '+(d.period?amount(d.rx_bytes):rate(d.rx_bps)),'lm-rx'));card.append(duplex,resources(d));if(d.alerts.length)card.title=d.alerts.map(x=>x.reason).join('\n');return card}
 function resourceCell(d){const cell=node('td');cell.append(resources(d));return cell}
 function renderRows(){if(!last)return;const hours=$('lm-period').value,historical=hours!=='live',filtered=$('lm-alert-only').checked;const body=$('lm-rows'),scroll=body.closest('.lm-table-scroll'),top=scroll.scrollTop;body.replaceChildren();$('lm-ranking-title').textContent='PC 통신량 TOP 50'+(historical?' · 최근 '+hours+'시간':'');$('lm-tx-heading').textContent=historical?'누적 송신 ↑':'송신 ↑';$('lm-rx-heading').textContent=historical?'누적 수신 ↓':'수신 ↓';$('lm-total-heading').textContent=historical?'누적 합계':'합계';$('lm-resource-heading').textContent=historical?'CPU / RAM 평균·최고':'CPU / RAM 현재·최고';
 if(historical&&(!ranking||ranking.hours!==Number(hours))){const tr=node('tr'),td=node('td',rankingError||'선택한 기간의 통신량을 집계하고 있습니다.','lm-muted');td.colSpan=7;tr.append(td);body.append(tr);$('lm-table-meta').textContent='서버 · TOP 5 · TOP 50에 같은 기간을 적용합니다.';return}
 const current=new Map(last.pcs.map(d=>[d.id,d]));const source=historical?ranking.pcs.map(d=>{const live=current.get(d.id);return {...d,period:true,connected_client_count:live?.connected_client_count,connections_partial:live?.connections_partial,cpu:d.cpu_avg,ram:d.ram_avg,alerts:live?.alerts||[],severity:live?.severity||'none',state:live?.state||'missing',comparison:live?.comparison||'수집 대기'}}):last.pcs;const all=filtered?source.filter(d=>d.alerts.length):source,rows=all.slice(0,50);
 for(const d of rows){const tr=node('tr',null,d.severity==='none'?'':'lm-row-'+d.severity);tr.append(node('td',d.rank||'—','lm-rank'));const device=node('td');device.append(node('div',d.label,'lm-device'),node('div',ip(d),'lm-ip'));const tx=node('td',historical?amount(d.tx_bytes):rate(d.tx_bps),'lm-tx'),rx=node('td',historical?amount(d.rx_bytes):rate(d.rx_bps),'lm-rx');tr.append(device,tx,rx,node('td',historical?amount(d.total_bytes):rate(d.total_bps)),resourceCell(d));const status=node('td');status.append(badge(d));for(const a of d.alerts)status.append(node('div',a.reason,'lm-table-reason'));if(!d.alerts.length)status.append(node('div',d.comparison,'lm-muted'));if(historical)status.append(node('div','기간 내 수집률 '+n(d.coverage_percent)+'%','lm-muted'));else status.append(node('div',clock(d.last_seen),'lm-muted'));tr.append(status);body.append(tr)}
 if(!rows.length){const tr=node('tr'),td=node('td',filtered?'현재 주의·경고로 표시된 PC가 없습니다.':'등록된 PC가 없습니다.','lm-muted');td.colSpan=7;tr.append(td);body.append(tr)}
 const stamp=x=>new Date(x).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});$('lm-table-meta').textContent=(rankingError?rankingError+' ':'')+(filtered?'주의·경고 PC ':'전체 PC ')+all.length+'대 중 '+rows.length+'대 표시 · '+(historical?'누적 송수신량 순위 · '+stamp(ranking.window_start)+' ~ '+stamp(ranking.window_end)+' (한국 시간) · 기간 집계 1분 갱신 · 주의·경고는 최신 수집 상태 기준':'최근 유효 송수신 속도 순위')+' · 미수집은 0으로 처리하지 않습니다.';scroll.scrollTop=top;
 }
 async function loadRanking(){const hours=$('lm-period').value;if(hours==='live'||!dialog.open)return;if(rankingController&&rankingPending===hours)return;rankingController?.abort();const request=new AbortController(),version=++rankingVersion;rankingController=request;rankingPending=hours;const timeout=setTimeout(()=>request.abort(),30000);try{const r=await fetch('api/traffic-ranking?hours='+encodeURIComponent(hours),{cache:'no-store',signal:request.signal});if(!r.ok)throw Error('ranking');const value=await r.json();if(version!==rankingVersion||!dialog.open||hours!==$('lm-period').value)return;ranking=value;rankingError='';renderScope()}catch(e){if(version!==rankingVersion||!dialog.open)return;rankingError=ranking?'기간별 자료 갱신이 지연되어 이전 집계를 표시합니다.':'기간별 자료를 불러오지 못했습니다. 잠시 후 다시 시도합니다.';renderScope()}finally{clearTimeout(timeout);if(version===rankingVersion){rankingController=null;rankingPending=''}}}
 function renderScope(){if(!last)return;const hours=$('lm-period').value,historical=hours!=='live';
 $('lm-server-title').textContent='서버 통신 현황'+(historical?' · 최근 '+hours+'시간':'');
 $('lm-top-title').textContent='PC 통신량 TOP 5'+(historical?' · 최근 '+hours+'시간':'');
 $('lm-top-note').textContent=historical?'기간 누적 송신 + 수신':'최근 수집 속도 · 송신 + 수신';
 $('lm-server-count').textContent='서버 '+last.counts.servers+'대';
 const ready=!historical||(ranking&&ranking.hours===Number(hours));
 $('lm-period-note').textContent='서버 · TOP 5 · TOP 50 공통 적용'+(historical?' · 기간 누적량 / CPU·RAM 평균·최고 · 주의·경고는 최신 상태':' · 최근 수집 속도 / CPU·RAM 현재·최근 5분 최고');
 if(!ready){for(const id of ['lm-servers','lm-top5'])$(id).replaceChildren(node('p',rankingError||'선택한 기간의 통신량을 집계하고 있습니다.','lm-loading'));renderRows();return}
 const current=new Map([...last.servers,...last.pcs].map(d=>[d.id,d]));
 const merge=d=>{const live=current.get(d.id);return {...d,period:true,connected_client_count:live?.connected_client_count,connections_partial:live?.connections_partial,cpu:d.cpu_avg,ram:d.ram_avg,alerts:live?.alerts||[],severity:live?.severity||'none',state:live?.state||'missing',comparison:live?.comparison||'수집 대기'}};
 const servers=historical?ranking.servers.map(merge):last.servers;
 const top=historical?ranking.pcs.filter(d=>d.total_bytes!=null).slice(0,5).map(merge):last.pcs.filter(d=>d.state==='live').slice(0,5);
 const scroll=$('lm-servers').scrollTop;$('lm-servers').replaceChildren(...servers.map(serverCard));$('lm-servers').scrollTop=scroll;
 if(!servers.length)$('lm-servers').append(node('p','등록된 서버가 없습니다.','lm-empty'));
 $('lm-top5').replaceChildren(...top.map(topCard));if(!top.length)$('lm-top5').append(node('p','해당 기간에 통신량이 수집된 PC가 없습니다.','lm-empty'));renderRows();
 }
 function render(data){last=data;const c=data.counts;$('lm-stats').replaceChildren();for(const [label,value,note,cls] of [['등록 장비',c.registered,'서버 '+c.servers+' · PC '+c.pcs,''],['최근 수집',c.live,'유효 통신량',''],['경고',c.warning,'확인 우선','lm-warning-text'],['주의',c.caution,'변화 확인','lm-caution-text'],['수집 지연·대기',c.delayed,'자료 확인','']]){const box=node('div',null,'lm-stat'),v=node('div',value,'lm-stat-value '+cls);v.append(node('small',note));box.append(node('div',label,'lm-stat-label'),v);$('lm-stats').append(box)}renderScope();$('lm-update').textContent='갱신 '+clock(data.generated_at)+' · 15초 간격';}
 async function refreshLive(){clearTimeout(timer);if(!dialog.open||document.hidden)return;const token=epoch;controller?.abort();controller=new AbortController();const request=controller;const timeout=setTimeout(()=>request.abort(),20000);try{const response=await fetch('api/live-monitor',{cache:'no-store',signal:request.signal});if(!response.ok)throw Error('load');const data=await response.json();if(token!==epoch||!dialog.open)return;render(data);loadRanking();$('lm-error').hidden=true;dialog.removeAttribute('data-outdated')}catch(e){if(token!==epoch||!dialog.open||document.hidden)return;$('lm-error').hidden=false;$('lm-error').textContent=last?'갱신하지 못했습니다. 아래는 '+clock(last.generated_at)+' 기준 이전 자료입니다. 연결을 다시 확인하고 있습니다.':'관제 자료를 불러오지 못했습니다. 잠시 후 자동으로 다시 시도합니다.';dialog.setAttribute('data-outdated','true');$('lm-update').textContent='갱신 지연'}finally{clearTimeout(timeout);if(token===epoch&&dialog.open&&!document.hidden)timer=setTimeout(refreshLive,15000)}}
 async function expand(){try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();ownsFullscreen=true}else if(ownsFullscreen){await document.exitFullscreen();ownsFullscreen=false}}catch(e){/* Browser-window layout is already full size. */}}
 $('live-open').onclick=()=>{if(dialog.open)return;epoch++;previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();expand();refreshLive()};
 $('lm-expand').onclick=expand;$('lm-close').onclick=()=>dialog.close();$('lm-alert-only').onchange=()=>{$('lm-rows').closest('.lm-table-scroll').scrollTop=0;renderRows()};$('lm-period').onchange=()=>{rankingVersion++;rankingController?.abort();rankingController=null;rankingPending='';ranking=null;rankingError='';$('lm-rows').closest('.lm-table-scroll').scrollTop=0;renderScope();loadRanking()};
 dialog.addEventListener('close',()=>{epoch++;clearTimeout(timer);controller?.abort();rankingVersion++;rankingController?.abort();rankingController=null;rankingPending='';document.body.style.overflow=previousOverflow;if(ownsFullscreen&&document.fullscreenElement)document.exitFullscreen().catch(()=>{});ownsFullscreen=false;$('live-open').focus()});
 document.addEventListener('visibilitychange',()=>{if(!dialog.open)return;if(document.hidden){clearTimeout(timer);controller?.abort();rankingVersion++;rankingController?.abort();rankingController=null;rankingPending=''}else refreshLive()});
 document.addEventListener('fullscreenchange',()=>{$('lm-expand').textContent=document.fullscreenElement?'전체화면 해제':'전체화면';if(!document.fullscreenElement)ownsFullscreen=false});
})();
