(()=>{'use strict';
 const main=document.querySelector('main'),header=document.querySelector('header');main.classList.add('portal-main');header.className='portal-header';header.innerHTML='<div class="portal-logo"><span class="brand-mark">N</span> NetChecker <span class="portal-tag">네트워크 보안 관리</span></div><div class="portal-actions"><button id="password-open">비밀번호 변경</button><button id="logout">로그아웃 ↗</button></div>';
 const nav=el('nav',null,'portal-nav');nav.setAttribute('aria-label','주요 메뉴');header.after(nav);const crumb=el('div',null,'portal-crumb');main.prepend(crumb);
 const welcome=el('section',null,'portal-welcome');welcome.innerHTML='<h2>네트워크 보안 관리 홈</h2><p class="muted">의심 흐름 조사부터 보고서 생성, 조치 후 개선 확인까지 한곳에서 진행하세요.</p>';
 const sections={defender:[$('defenderdevices').closest('section')],home:[],servers:[$('servermonitor').closest('section')],traffic:[$('trafficdevices').closest('section')],devices:[$('devices').closest('section')],pending:[$('pending').closest('section')],agent:[$('executionlog').closest('section')]};
 const grid=$('network').closest('.grid'),history=$('history').closest('section'),result=$('result');const home=el('div');home.append(welcome,grid,history,result);sections.home=[home];main.insertBefore(home,$('pending').closest('section'));
 let current='home';const names={defender:'AI 디펜더 모니터링',home:'홈',servers:'서버 통신량·접속 장비',traffic:'통신량 모니터링',devices:'장비 수집 현황',pending:'등록 대기',agent:'Agent 주요 작업'};
 function navigate(id){if(!sections[id])id='home';current=id;for(const [key,items] of Object.entries(sections))for(const item of items)item.hidden=key!==id;for(const b of nav.querySelectorAll('[data-page]')){b.classList.toggle('active',b.dataset.page===id);b.setAttribute('aria-current',b.dataset.page===id?'page':'false')}crumb.textContent='NetChecker / '+names[id];historyState(id);if(id==='servers')safe(loadServerOverview);if(id==='pending')toast.hidden=true;window.scrollTo({top:0,behavior:'smooth'})}
 function historyState(id){if(location.hash!=='#'+id)window.history.replaceState(null,'','#'+id)}
 for(const [id,name] of Object.entries(names)){const b=el('button',name);b.dataset.page=id;b.onclick=()=>navigate(id);nav.append(b)}const live=el('button','실시간 보기 ↗');live.onclick=()=>$('live-open').click();nav.append(live);
 const toast=el('aside',null,'request-toast');toast.hidden=true;toast.setAttribute('aria-live','polite');toast.innerHTML='<button class="toast-close" aria-label="알림 닫기">×</button><strong>새 장비 등록 요청</strong><p id="request-caption"></p><button id="request-jump">등록 요청 확인 →</button>';document.body.append(toast);toast.querySelector('.toast-close').onclick=()=>toast.hidden=true;$('request-jump').onclick=()=>navigate('pending');
 let seenPending=new Set();window.portalRefresh=s=>{const ids=new Set(s.pending.map(d=>d.installation_id));const fresh=[...ids].some(id=>!seenPending.has(id));seenPending=ids;nav.querySelector('[data-page=pending]').textContent='등록 대기'+(ids.size?' ('+ids.size+')':'');if(!ids.size)toast.hidden=true;else if(fresh&&current!=='pending'){$('request-caption').textContent=ids.size+'대의 장비가 승인을 기다리고 있습니다.';toast.hidden=false}window.refreshVerificationList?.()};
 function layer(title,body){const d=el('dialog',null,'layer');const head=el('div',null,'layer-head');head.append(el('h2',title));const close=el('button','×');close.type='button';close.setAttribute('aria-label','닫기');close.onclick=()=>d.close();head.append(close);const content=el('div',null,'layer-body');content.append(body);d.append(head,content);d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();return d}
 window.portalLayer=layer;
 window.openPortPolicy=d=>{const form=el('form');form.innerHTML='<p>허용된 업무 서비스 포트를 입력하세요. 이 설정은 분석 기준이며 서버 방화벽을 변경하지 않습니다.</p><label for="policy-tcp">TCP 포트</label><textarea id="policy-tcp" rows="3" placeholder="예: 80, 443, 445 또는 한 줄에 하나씩 입력"></textarea><label for="policy-udp">UDP 포트</label><textarea id="policy-udp" rows="3" placeholder="예: 53, 123 또는 한 줄에 하나씩 입력"></textarea><p>여러 포트를 쉼표·공백·줄바꿈으로 구분해 입력하세요. TCP·UDP 각각 최대 200개까지 저장합니다.</p><p class="form-error" role="alert"></p><div class="row"><button type="submit">설정 저장</button></div>';const modal=layer(d.label+' · 허용 포트 설정',form);form.querySelector('#policy-tcp').value=d.policy.tcp.join(', ');form.querySelector('#policy-udp').value=d.policy.udp.join(', ');form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;try{const parse=v=>{if(!v.trim())return [];const parts=v.trim().split(/[\s,;，]+/).filter(Boolean);if(new Set(parts).size>200)throw Error('각각 최대 200개까지 입력할 수 있습니다.');if(parts.some(x=>!/^\d+$/.test(x)||+x<1||+x>65535))throw Error('포트는 1~65535 사이의 숫자로 입력해주세요.');return [...new Set(parts.map(Number))]};await api('devices/'+d.id+'/policy','PUT',{configured:true,tcp:parse($('policy-tcp').value),udp:parse($('policy-udp').value)});modal.close();trafficUpdated=0;await loadServerOverview()}catch(e){form.querySelector('.form-error').textContent=e.message}finally{b.disabled=false}}};
 $('password-open').onclick=()=>{const f=el('form');f.innerHTML='<p>비밀번호를 변경하면 모든 로그인 세션이 종료됩니다.</p><label for="pw-current">현재 비밀번호</label><input id="pw-current" type="password" autocomplete="current-password" required><label for="pw-new">새 비밀번호 · 12자 이상</label><input id="pw-new" type="password" autocomplete="new-password" minlength="12" maxlength="128" required><label for="pw-confirm">새 비밀번호 확인</label><input id="pw-confirm" type="password" autocomplete="new-password" required><p class="form-error" role="alert"></p><div class="row"><button>비밀번호 변경</button></div>';layer('비밀번호 변경',f);f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;try{if($('pw-new').value!==$('pw-confirm').value)throw Error('새 비밀번호가 서로 다릅니다.');await api('password','POST',{current:$('pw-current').value,password:$('pw-new').value});location.replace('login')}catch(e){f.querySelector('.form-error').textContent=e.message}finally{b.disabled=false}}};
 $('logout').onclick=()=>safe(async()=>{await api('logout','POST',{});location.replace('login')});
 const serverPanel=sections.servers[0],intro=serverPanel.querySelector('.muted');intro.textContent='선택한 기간의 서버 통신량과 서버에서 관측한 상대 장비를 확인합니다.';const filters=el('form',null,'portal-toolbar');filters.innerHTML='<label>조회 기간<select id="server-hours"><option value="today">오늘</option><option value="0">실시간 · 최근 5분</option>'+[1,2,4,6,8,12,24].map(h=>'<option value="'+h+'">최근 '+h+'시간</option>').join('')+'</select></label><label>서버·접속 장비 IP<input id="server-ip" placeholder="예: 192.0.2.10" maxlength="45"></label><button>조회</button><button type="button" id="server-reset" class="secondary">초기화</button>';intro.after(filters);const note=el('p','조회 중입니다.','portal-period-note');filters.after(note);let requestVersion=0;
 async function loadServerOverview(){const version=++requestVersion,params=new URLSearchParams(),hours=$('server-hours').value,ip=$('server-ip').value.trim();if(hours!=='today')params.set('hours',hours);if(ip)params.set('ip',ip);const data=await api('server-overview?'+params);if(version!==requestVersion)return;renderServers($('servermonitor'),data,true);note.textContent='조회 범위: '+localKst(data.window_start)+' ~ '+localKst(data.window_end)+(ip?' · IP 검색: '+ip:'')+' · 상대별 통신량은 해당 구간에 종료된 수집 기록 기준입니다.';if(!data.servers.length)$('servermonitor').textContent='조건에 맞는 서버 또는 접속 장비가 없습니다.'}
 window.loadServerOverview=loadServerOverview;filters.onsubmit=e=>{e.preventDefault();safe(loadServerOverview)};$('server-hours').onchange=()=>safe(loadServerOverview);$('server-reset').onclick=()=>{$('server-ip').value='';$('server-hours').value='today';safe(loadServerOverview)};
 window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));navigate(location.hash.slice(1)||'home');
})();

(()=>{'use strict';
 let selected=null,devices=[],generation=0,busy=false;
 const box=el('section',null,'panel');box.hidden=true;box.innerHTML='<div class="row"><h2>조치 후 개선 확인</h2><button id="verification-open">조치 기록·개선 확인</button></div><p class="muted">조치 전후의 통신량과 CPU·RAM을 비교합니다. 담당자 메모는 서버에만 보관하고 AI에는 조치 유형과 집계 자료를 전달합니다.</p><div id="verification-list"></div>';$('result').after(box);
 const oldRefresh=window.portalRefresh;window.portalRefresh=s=>{devices=s.devices.filter(d=>d.active);oldRefresh(s)};
 const log=el('div');$('executionlog').after(log);
 const popupButton=el('button','조치 기록·개선 확인');popupButton.style.cssText='margin:0 24px 24px';popupButton.hidden=true;$('networkdialog').append(popupButton);
 window.clearVerificationReport=id=>{if(selected?.id===id){selected=null;generation++;box.hidden=true;popupButton.hidden=true;log.replaceChildren();$('verification-list').replaceChildren()}};
 window.setVerificationReport=r=>{if(selected?.id!==r.id){generation++;$('verification-list').replaceChildren();log.replaceChildren()}selected=r;box.hidden=r.payload.kind!=='network'||r.status!=='done';popupButton.hidden=box.hidden;if(!box.hidden)refreshChecks()};
 async function refreshChecks(){if(!selected||selected.payload.kind!=='network'||selected.status!=='done'||busy)return;busy=true;const id=selected.id,version=generation;try{const rows=await api('verifications?report_id='+encodeURIComponent(id));if(version!==generation||selected?.id!==id)return;const area=$('verification-list');area.replaceChildren();log.replaceChildren();if(!rows.length){area.append(el('p','아직 등록된 조치가 없습니다.','muted'));return}log.append(el('h3','조치 후 개선 확인 작업'));for(const r of rows){const p=r.payload,card=el('article',null,'verification-box'),state={waiting:'자료 수집·실행 대기',running:'Agent 확인 중',done:'확인 완료',failed:'확인 미완료'}[r.status];card.append(el('h3',p.action_kind+' · '+(labels[p.device_id]||p.device_id)),el('p','조치 '+localKst(p.action_at)+' · 전후 각 '+p.minutes+'분 · '+state,'muted'));if(p.note)card.append(el('p','담당자 메모: '+p.note));if(r.status==='waiting')card.append(el('p',localKst(r.due)+' 이후 순차 확인합니다. 화면을 닫아도 예약은 유지됩니다.','muted'));if(p.error)card.append(el('p',p.error));if(p.comparison){const c=p.comparison;tableInto(card,['지표','조치 전','조치 후'],[['평균 통신 속도',number(c.before.average_mbps)+' Mbps',number(c.after.average_mbps)+' Mbps'],['평균 CPU',percent(c.before.cpu_avg),percent(c.after.cpu_avg)],['평균 RAM',percent(c.before.ram_avg),percent(c.after.ram_avg)],['통신량 수집률',percent(c.before.coverage_percent),percent(c.after.coverage_percent)]])}if(p.result){card.append(el('h3',({improved:'관측 지표 개선',persistent:'문제 지속·추가 확인 필요',insufficient:'자료 부족·판단 보류'})[p.result.verdict]),el('p',p.result.summary),el('p','다음 확인: '+p.result.next_action));const feedback=el('div',null,'row');for(const [value,title] of [['improved','업무 속도도 개선됨'],['still_slow','여전히 느림'],['unknown','확인 전']]){const b=el('button',title,p.feedback?.value===value?'':'secondary');b.onclick=()=>safe(async()=>{await api('verifications/'+r.id+'/feedback','POST',{value});await refreshChecks()});feedback.append(b)}card.append(feedback);if(p.feedback?.value==='still_slow')card.append(el('p','추가로 확인한 조치를 기록하면 이전 피드백과 함께 다시 조사합니다.','muted'))}const traces=(p.trace||[]).filter(t=>!['도구 실행 시작','도구 실행 완료'].includes(t.action));if(traces.length){const details=el('details');details.append(el('summary','Agent 주요 작업'));for(const t of traces.slice(-6)){details.append(el('p',t.action+' · '+t.detail,'verification-logs'));log.append(el('p',t.action+' · '+t.detail,'verification-logs'))}card.append(details)}area.append(card)}}catch(e){$('verification-list').textContent=e.message}finally{busy=false}}
 window.refreshVerificationList=refreshChecks;
 function open(){if(!selected||selected.status!=='done')return;const reportId=selected.id;const f=el('form');f.innerHTML='<label for="verify-device">대상 장비</label><select id="verify-device" required></select><label for="verify-kind">조치 유형</label><select id="verify-kind">'+['파일 전송 중단','백업 작업 조정','프로그램 종료','자원 확보','기타 조치'].map(x=>'<option>'+x+'</option>').join('')+'</select><label for="verify-note">담당자 메모 · 선택</label><textarea id="verify-note" maxlength="1000" placeholder="실제 수행한 조치를 기록하세요"></textarea><label for="verify-time">조치 시각 · 한국 시간</label><input id="verify-time" type="datetime-local" required><label for="verify-minutes">조치 전후 비교 구간</label><select id="verify-minutes"><option value="10">각 10분</option><option value="30">각 30분</option><option value="60">각 1시간</option></select><p>지금 조치했다면 이후 자료가 쌓인 뒤 자동 확인합니다. 수집 전송을 고려해 비교 구간 종료 후 90초부터 실행합니다. 분석 결과는 실제 업무 응답 속도와 다를 수 있습니다.</p><p class="form-error" role="alert"></p><div class="row"><button>기록하고 개선 확인 예약</button></div>';const modal=window.portalLayer('조치 기록·개선 확인',f);for(const d of devices){const o=el('option',d.label+' · '+(JSON.parse(d.ips||'[]').join(' / ')||'IP 미확인'));o.value=d.id;$('verify-device').append(o)}const candidate=selected.payload.network_report?.candidates?.[0]?.id;if(candidate&&devices.some(d=>d.id===candidate))$('verify-device').value=candidate;$('verify-time').value=new Date(Date.now()+9*3600000).toISOString().slice(0,16);f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;try{await api('verifications','POST',{report_id:reportId,device_id:$('verify-device').value,action_kind:$('verify-kind').value,note:$('verify-note').value,action_at:new Date($('verify-time').value+':00+09:00').toISOString(),minutes:Number($('verify-minutes').value)});modal.close();if(networkDialog.open)networkDialog.close();await refreshChecks();box.scrollIntoView({behavior:'smooth'})}catch(e){f.querySelector('.form-error').textContent=e.message}finally{b.disabled=false}}}
 $('verification-open').onclick=open;popupButton.onclick=open;
})();

(()=>{
 const section=$('executionlog').closest('section');for(const child of section.children)child.hidden=true;
 const panel=el('div');section.append(panel);panel.append(el('h2','Agent 주요 작업'),el('p','실행 날짜(한국 시간)별 작업 기록입니다. 완료 후와 보고서 삭제 후에도 보관되며, 이 화면은 15초마다 갱신됩니다.','muted'));
 const form=el('form',null,'portal-toolbar'),label=el('label','실행 날짜'),date=el('input');date.type='date';date.required=true;date.value=new Date(Date.now()+9*3600000).toISOString().slice(0,10);label.append(date);form.append(label,el('button','조회'));panel.append(form);
 const info=el('p',null,'muted'),list=el('div'),pages=el('div',null,'row'),prev=el('button','이전','secondary'),next=el('button','다음','secondary');pages.append(prev,next);panel.append(info,list,pages);let offset=0,version=0;
 async function load(){const v=++version;try{const data=await api('agent-work-logs?day='+encodeURIComponent(date.value)+'&offset='+offset);if(v!==version)return;info.textContent=date.value+' · 총 '+data.total+'건 · 실행 기록이 없으면 해당 날짜에 분석 작업이 없었던 것입니다.';list.replaceChildren();for(const r of data.items){const card=el('article',null,'finding'),status={waiting:'예약 대기',running:'실행 중',done:'완료',failed:'실패'}[r.status]||r.status;card.append(el('h3',r.title+' · '+status),el('p','시작 '+local(r.created),'muted'));if(r.summary)card.append(el('p',r.summary));const steps=el('div');if(r.steps.length)renderTraceSummary(steps,r.steps);else steps.append(el('p',r.status==='running'?'작업 시작 · 실행 기록을 기다리고 있습니다.':r.status==='waiting'?'예약 시각에 실행합니다.':'세부 작업 기록이 없습니다.','muted'));card.append(steps);list.append(card)}if(!data.items.length)list.append(el('p','이 날짜의 작업 기록이 없습니다.'));prev.disabled=offset===0;next.disabled=offset+50>=data.total}catch(e){if(v===version)info.textContent='작업 기록 조회 실패: '+e.message}}
 form.onsubmit=e=>{e.preventDefault();offset=0;load()};prev.onclick=()=>{offset=Math.max(0,offset-50);load()};next.onclick=()=>{offset+=50;load()};setInterval(()=>{if(!section.hidden)load()},15000);load();
})();

(()=>{
 const button=el('button','외부 연동 설정');document.querySelector('.portal-actions').prepend(button);
 button.onclick=async()=>{try{const conf=await api('integrations'),form=el('form');form.innerHTML='<p>사업장: 경남 창원·함안·밀양 / 경기 의왕</p><p>비밀 인증키는 서버에만 보관합니다. JavaScript 키는 직접 공유를 위해 브라우저에서 사용합니다. 빈 칸으로 저장하면 기존 키를 유지합니다.</p><label>공공데이터포털 일반 인증키(Decoding)</label><input name="public_key" type="password" autocomplete="new-password"><label>카카오 REST API 키</label><input name="kakao_key" type="password" autocomplete="new-password"><label>카카오 Client Secret</label><input name="kakao_secret" type="password" autocomplete="new-password"><label>카카오 JavaScript 키 · 직접 공유용</label><input name="kakao_js_key" type="password" autocomplete="new-password" pattern="[a-fA-F0-9]{32}" placeholder="카카오 앱의 JavaScript 키"><p class="muted">카카오 개발자 콘솔의 JavaScript SDK 도메인과 제품 링크 웹 도메인에 https://netchecker.example.com 을 등록해 주세요. REST API 키와는 다릅니다.</p><label class="integration-check"><input name="auto_notify" type="checkbox"> 카카오 자동 알림 켜기 (분석 완료·실패 시)</label><label class="integration-check"><input name="notify_self" type="checkbox"> 발신자 본인에게도 알림 받기 (나와의 채팅방)</label><p class="muted">자동 알림을 켜면 분석 완료·실패 시 선택한 수신 대상에게 발송합니다. 본인만 받으려면 본인 수신을 체크하고 담당자는 선택하지 마세요.</p><button>설정 저장</button><p class="integration-status"></p>';
 form.elements.auto_notify.checked=conf.auto_notify;form.elements.notify_self.checked=!!conf.notify_self;const notice=form.querySelector('.integration-status');notice.textContent='공공키 '+(conf.public_key_set?'저장됨':'미설정')+' / 카카오 '+(conf.connected?'연결됨':'미연결')+' / 직접 공유 '+(conf.kakao_js_key_set?'설정됨':'키 미설정')+' / 선택 담당자 '+conf.recipients.length+'명';
 const help=el('p','카카오 Redirect URI: '+conf.redirect_uri,'muted');form.append(help);const actions=el('div',null,'row');form.append(actions);const area=el('div');form.append(area);
 function action(label,fn){const b=el('button',label,'secondary');b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){notice.textContent=e.message}finally{b.disabled=false}};actions.append(b)}
 action('카카오 발신 계정 연결',async()=>{const r=await api('integrations/kakao/connect','POST',{});location.href=r.url});
 action('담당자 등록 링크 만들기',async()=>{const r=await api('integrations/kakao/recipient-invite','POST',{});area.replaceChildren(el('p','24시간 동안 유효한 링크입니다. 수신 담당자에게 전달해 카카오 로그인·동의를 요청하세요. 담당자가 완료하면 수신 담당자 목록을 다시 조회해 선택·저장해 주세요.'));const input=el('input');input.value=r.url;input.readOnly=true;input.setAttribute('aria-label','담당자 등록 링크');const copy=el('button','등록 링크 복사');copy.type='button';copy.onclick=async()=>{try{await navigator.clipboard.writeText(r.url);notice.textContent='등록 링크를 복사했습니다.'}catch(e){input.focus();input.select();notice.textContent='선택된 링크를 직접 복사해 주세요.'}};area.append(input,copy)});
 action('자동 알림 수신 담당자 선택',async()=>{const rows=await api('integrations/kakao/friends');area.replaceChildren();const picked=new Set(conf.recipients.map(x=>x.uuid));const checks=[];for(const r of rows){const l=el('label',r.name),input=el('input');input.type='checkbox';input.checked=picked.has(r.uuid);l.prepend(input);area.append(l);checks.push([input,r.uuid])}if(!rows.length)area.append(el('p','조회 가능한 담당자가 없습니다. 발신자와 카카오 친구인지, 같은 앱 연결·friends/talk_message 동의·사용 권한을 확인하세요.'));const save=el('button','선택 담당자 저장');save.type='button';save.onclick=async()=>{try{const r=await api('integrations/kakao/recipients','POST',{uuids:checks.filter(x=>x[0].checked).map(x=>x[1])});notice.textContent=r.recipients.length+'명 저장됨'}catch(e){notice.textContent=e.message}};area.append(save)});
 action('카카오톡으로 직접 공유',()=>window.openKakaoReportShare());
 action('오늘 공공데이터 조회 확인',async()=>{const day=new Date(Date.now()+9*3600000).toISOString().slice(0,10),r=await api('integrations/context?day='+day);area.replaceChildren(el('pre',JSON.stringify(r,null,2)))});
 action('카카오 연결 해제',async()=>{await api('integrations/kakao/disconnect','POST',{});notice.textContent='연결 해제 및 자동 발송 중지'});
 form.onsubmit=async e=>{e.preventDefault();try{await api('integrations','POST',{public_key:form.elements.public_key.value,kakao_key:form.elements.kakao_key.value,kakao_secret:form.elements.kakao_secret.value,kakao_js_key:form.elements.kakao_js_key.value.trim(),auto_notify:form.elements.auto_notify.checked,notify_self:form.elements.notify_self.checked});for(const n of ['public_key','kakao_key','kakao_secret','kakao_js_key'])form.elements[n].value='';notice.textContent='설정 저장 완료'}catch(e){notice.textContent=e.message}};
 const logs=el('div');logs.append(el('h3','최근 카카오 발송 기록'));for(const row of conf.deliveries)logs.append(el('p',local(row.created)+' · '+row.status+' · '+row.detail));form.append(logs);window.portalLayer('공공데이터·카카오 연동',form);
 }catch(e){$('message').textContent=e.message}};
})();

(()=>{'use strict';
 let selected=null,sdkPromise=null,initializedKey=null;
 const button=el('button','카카오톡으로 공유','secondary');button.type='button';button.hidden=true;button.style.cssText='background:#fee500;color:#191919';$('pdfdownload').after(button);
 window.setKakaoShareReport=r=>{selected=r;button.hidden=!r||r.status==='running';};
 function loadSdk(){if(window.Kakao)return Promise.resolve();if(sdkPromise)return sdkPromise;
 sdkPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://t1.kakaocdn.net/kakao_js_sdk/2.8.3/kakao.min.js';script.integrity='sha384-oroumrnFVE0xtgqyDZJARgERibXg2C28380uaUZz2kHDS5CR7tu20eGiOU6GkTpy';script.crossOrigin='anonymous';script.onload=()=>resolve();script.onerror=()=>{script.remove();sdkPromise=null;reject(Error('카카오 공유 기능을 불러오지 못했습니다. 네트워크 연결을 확인하고 다시 시도해 주세요.'));};document.head.append(script);});return sdkPromise;}
 window.openKakaoReportShare=async()=>{
  const id=selected?.id;if(!id||selected.status==='running')throw Error('분석 이력에서 완료된 보고서를 먼저 선택해 주세요.');
  const body=el('div'),notice=el('p','공유 내용을 준비하고 있습니다.','muted'),preview=el('p'),send=el('button','카카오톡 친구·채팅방 선택');send.type='button';send.disabled=true;send.style.cssText='background:#fee500;color:#191919';
  body.append(el('p','친구나 채팅방을 직접 선택해 보고서 링크를 보냅니다. 자동 알림 수신자로 저장되지는 않습니다. 받은 사람도 NetChecker 로그인이 필요합니다.'),preview,send,notice);window.portalLayer('카카오톡으로 보고서 공유',body);
  try{const config=await api('integrations/kakao/share-config?report_id='+encodeURIComponent(id));preview.textContent=config.template.text;await loadSdk();if(initializedKey!==config.javascript_key){if(Kakao.isInitialized())Kakao.cleanup();Kakao.init(config.javascript_key);initializedKey=config.javascript_key;}send.disabled=false;notice.textContent='선택 화면에서 수신자를 고르고 전송해 주세요.';
   send.onclick=()=>{try{const result=Kakao.Share.sendDefault(config.template);notice.textContent='카카오톡 선택 화면에서 전송을 완료해 주세요. 이 화면에서는 실제 전달 여부를 확인하지 않습니다.';if(result?.catch)result.catch(()=>{notice.textContent='공유를 시작하지 못했습니다. 팝업 허용과 카카오 앱의 도메인 설정을 확인해 주세요.';});}catch(e){notice.textContent='공유를 시작하지 못했습니다. 팝업 허용과 JavaScript 키·도메인 설정을 확인해 주세요.';}};
  }catch(e){notice.textContent=e.message;}
 };
 button.onclick=()=>safe(()=>window.openKakaoReportShare());
})();
